apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: codimon/users
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: NODE_ENV
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: APP_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: JWT_EXPIRES_IN
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: MYSQL_DATABASE
            - name: DB_SOCKET_PATH
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: DB_SOCKET_PATH
            - name: CLOUD_SQL_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: codimon-secrets
                  key: CLOUD_SQL_CONNECTION_NAME
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 4000
      targetPort: 3003